# --- Global Configuration ---
regtest=1
server=1
daemon=1
txindex=1
rpcuser=bootcamp
rpcpassword=bootcamp123

# --- Regtest Network Section ---
[regtest]
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=18443
fallbackfee=0.00001

